// Russian translations for field labels and descriptions.
// Keys are in camelCase to match Hermes's defineFieldCopy output (post-flatten).
// Used by ru.ts via `fieldLabels: RU_FIELD_LABELS` (see ru.ts L299).
//
// Idempotent install: re-running apply-i18n-patches.py overwrites this file.

export const RU_FIELD_LABELS: Record<string, string> = {
  // model / display
  model: 'Модель по умолчанию',
  modelContextLength: 'Окно контекста',
  fallbackProviders: 'Резервные модели',
  toolsets: 'Включённые наборы инструментов',
  timezone: 'Часовой пояс',
  'display.personality': 'Личность',
  'display.showReasoning': 'Блоки рассуждений',
  // agent
  'agent.maxTurns': 'Макс. шагов агента',
  'agent.imageInputMode': 'Вложения изображений',
  'agent.apiMaxRetries': 'Лимит API-повторов',
  'agent.serviceTier': 'Service Tier',
  'agent.toolUseEnforcement': 'Принудительный Tool-Use',
  // terminal / workspace
  'terminal.cwd': 'Рабочая директория',
  'terminal.backend': 'Бэкенд выполнения',
  'terminal.timeout': 'Тайм-аут команды',
  'terminal.persistentShell': 'Постоянная оболочка',
  'terminal.envPassthrough': 'Передача переменных окружения',
  'terminal.dockerImage': 'Docker Image',
  'terminal.singularityImage': 'Singularity Image',
  'terminal.modalImage': 'Modal Image',
  'terminal.daytonaImage': 'Daytona Image',
  // tool output / file read
  fileReadMaxChars: 'Лимит чтения файла',
  'toolOutput.maxBytes': 'Лимит вывода терминала',
  'toolOutput.maxLines': 'Лимит страницы файла',
  'toolOutput.maxLineLength': 'Лимит длины строки',
  // code execution / approvals / MCP
  'codeExecution.mode': 'Режим выполнения кода',
  'approvals.mode': 'Режим подтверждений',
  'approvals.timeout': 'Тайм-аут подтверждения',
  'approvals.mcpReloadConfirm': 'Подтверждать перезагрузку MCP',
  // security
  commandAllowlist: 'Белый список команд',
  'security.redactSecrets': 'Скрывать секреты',
  'security.allowPrivateUrls': 'Разрешить приватные URL',
  'browser.allowPrivateUrls': 'Приватные URL в браузере',
  // updates
  'updates.nonInteractiveLocalChanges': 'Локальные изменения при апдейте',
  // chat / sidebar sections
  chat: 'Чат',
  display: 'Внешний вид',
  workspace: 'Рабочая область',
  security: 'Безопасность',
  'memoryContext': 'Память и контекст',
  voice: 'Голос',
  advanced: 'Дополнительно',
  notifications: 'Уведомления',
  providers: 'Провайдеры',
  gateway: 'Шлюз',
  'keysTools': 'Инструменты и ключи',
  sessions: 'Архивные чаты',
  about: 'О приложении',
  // appearance sections
  inlineEmbeds: 'Inline-вставки',
  pet: 'Питомец',
  // subagents
  'delegation.model': 'Модель сабагента',
  'delegation.provider': 'Провайдер сабагента',
  'delegation.maxIterations': 'Лимит ходов сабагента',
  'delegation.maxConcurrentChildren': 'Параллельные сабагенты',
  'delegation.childTimeoutSeconds': 'Тайм-аут сабагента',
  'delegation.reasoningEffort': 'Усилие рассуждения сабагента',
  // memory
  'memory.memoryEnabled': 'Постоянная память',
  'memory.userProfileEnabled': 'Профиль пользователя',
  'memory.memoryCharLimit': 'Лимит постоянной памяти',
  'memory.userCharLimit': 'Лимит профиля',
  'memory.provider': 'Провайдер памяти',
  'context.engine': 'Контекстный движок',
  'compression.enabled': 'Авто-сжатие',
  'compression.threshold': 'Порог сжатия',
  'compression.targetRatio': 'Цель сжатия',
  'compression.protectLastN': 'Защищать недавние сообщения',
  // voice (flattened dot-keys)
  'tts.provider': 'Text-To-Speech Provider',
  'tts.edge.voice': 'Голос Edge',
  'tts.openai.model': 'OpenAI TTS Model',
  'tts.openai.voice': 'OpenAI Voice',
  'tts.elevenlabs.voiceId': 'ElevenLabs Voice',
  'tts.elevenlabs.modelId': 'ElevenLabs Model',
  'tts.xai.voiceId': 'xAI (Grok) Voice',
  'tts.xai.language': 'xAI Language',
  'tts.minimax.model': 'MiniMax TTS Model',
  'tts.minimax.voiceId': 'MiniMax Voice',
  'tts.mistral.model': 'Mistral TTS Model',
  'tts.mistral.voiceId': 'Mistral Voice',
  'tts.gemini.model': 'Gemini TTS Model',
  'tts.gemini.voice': 'Gemini Voice',
  'tts.neutts.model': 'NeuTTS Model',
  'tts.neutts.device': 'NeuTTS Device',
  'tts.kittentts.model': 'KittenTTS Model',
  'tts.kittentts.voice': 'KittenTTS Voice',
  'tts.piper.voice': 'Piper Voice',
  'voice.autoTts': 'Авто-озвучка ответов',
  'stt.provider': 'Speech-To-Text Provider',
  'stt.local.model': 'Локальная модель',
  'stt.local.language': 'Язык транскрипции',
  'stt.openai.model': 'OpenAI STT Model',
  'stt.groq.model': 'Groq STT Model',
  'stt.mistral.model': 'Mistral STT Model',
  'stt.elevenlabs.modelId': 'ElevenLabs STT Model',
  'stt.elevenlabs.languageCode': 'ElevenLabs Language',
  'stt.elevenlabs.tagAudioEvents': 'Tag Audio Events',
  'stt.elevenlabs.diarize': 'Speaker Diarization',
  'voice.recordKey': 'Голосовая команда',
  'voice.maxRecordingSeconds': 'Макс. длина записи',
  // file checkpoints (advanced)
  checkpoints: 'Контрольные точки файлов',
  // theme mode options
  light: 'Светлая',
  dark: 'Тёмная',
  system: 'Системная',
}

export const RU_FIELD_DESCRIPTIONS: Record<string, string> = {
  model: 'Основная модель для ответов. Fallback-модели используются при ошибке.',
  modelContextLength: 'Максимальное количество токенов в окне контекста.',
  fallbackProviders: 'Дополнительные провайдеры на случай отказа основного.',
  toolsets: 'Наборы инструментов, доступные агенту.',
  timezone: 'Часовой пояс для отображения времени.',
  'display.personality': 'Файл личности (AGENTS.md / SOUL.md).',
  'display.showReasoning': 'Показывать блоки рассуждений модели.',
  'agent.maxTurns': 'Максимальное количество итераций агента за один запрос.',
  'agent.imageInputMode': 'Как обрабатывать вложенные изображения.',
  'agent.apiMaxRetries': 'Сколько раз повторять API-запрос при временных ошибках.',
  'agent.serviceTier': 'Тарифный план API (OpenAI/Anthropic).',
  'agent.toolUseEnforcement': 'Принудительно использовать инструменты.',
  'terminal.cwd': 'Рабочая директория для команд терминала.',
  'terminal.backend': 'Где выполнять команды: локально, Docker, SSH.',
  'terminal.timeout': 'Сколько секунд ждать завершения команды.',
  'terminal.persistentShell': 'Сохранять состояние оболочки между командами.',
  'terminal.envPassthrough': 'Какие переменные окружения передавать в терминал.',
  'terminal.dockerImage': 'Образ Docker-контейнера, когда бэкенд — Docker.',
  'terminal.singularityImage': 'Образ, когда бэкенд — Singularity.',
  'terminal.modalImage': 'Образ, когда бэкенд — Modal.',
  'terminal.daytonaImage': 'Образ, когда бэкенд — Daytona.',
  fileReadMaxChars: 'Максимум символов при чтении файла.',
  'toolOutput.maxBytes': 'Максимальный размер вывода терминала в байтах.',
  'toolOutput.maxLines': 'Максимум строк на страницу вывода.',
  'toolOutput.maxLineLength': 'Обрезать строки длиннее этого значения.',
  'codeExecution.mode': 'Как выполнять код: безопасно, с подтверждением или без ограничений.',
  'approvals.mode': 'Когда запрашивать подтверждение перед выполнением.',
  'approvals.timeout': 'Сколько ждать ответа пользователя.',
  'approvals.mcpReloadConfirm': 'Спрашивать разрешение перед перезагрузкой MCP-серверов.',
  commandAllowlist: 'Команды, которые можно выполнять без подтверждения.',
  'security.redactSecrets': 'Автоматически скрывать API-ключи и пароли в выводе.',
  'security.allowPrivateUrls': 'Разрешить доступ к localhost и внутренним адресам.',
  'browser.allowPrivateUrls': 'Разрешить браузеру открывать приватные URL.',
  'memory.memoryEnabled': 'Включить постоянную память.',
  'memory.userProfileEnabled': 'Включить профиль пользователя.',
  'memory.provider': 'Плагин провайдера памяти.',
  'compression.enabled': 'Суммировать старый контекст, когда разговоры большие.',
  'compression.protectLastN': 'Не сжимать последние N сообщений.',
  'voice.autoTts': 'Автоматически озвучивать ответы.',
  'stt.local.model': 'Локальная модель для транскрипции.',
  'stt.local.language': 'Язык для локальной транскрипции.',
  'stt.elevenlabs.languageCode': 'Опциональный ISO-639-3 код языка. Пусто — ElevenLabs определит автоматически.',
  'voice.maxRecordingSeconds': 'Максимальная длина одной записи в секундах.',
}
